name: Run Pytest with Allure on Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    name: Run Tests on s3-runner
    runs-on: [self-hosted, s3-runner]  # Use your labeled self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Allure CLI
        shell: powershell
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force

          if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
            irm get.scoop.sh | iex
            $scoopPath = "$env:USERPROFILE\scoop\shims"
            $env:PATH += ";$scoopPath"
          }

          "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          scoop bucket add java | Out-Null
          scoop install allure | Out-Null

          allure --version
          java -version


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest with Allure
        run: |
          pytest test_always_pass.py test_always_fail.py test_calculator_app.py --alluredir=allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          pip install allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report